set_property IOSTANDARD LVCMOS33 [get_ports {sa[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports click_a]
set_property IOSTANDARD LVCMOS33 [get_ports click_b]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports mode1]
set_property IOSTANDARD LVCMOS33 [get_ports mode2]



set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets rst_IBUF]



set_property PACKAGE_PIN V20 [get_ports {sa[3]}]
set_property PACKAGE_PIN V18 [get_ports {sa[4]}]
set_property PACKAGE_PIN U20 [get_ports {sa[2]}]
set_property PACKAGE_PIN W21 [get_ports {sa[1]}]
set_property PACKAGE_PIN W20 [get_ports {sa[0]}]
set_property PACKAGE_PIN V19 [get_ports {sa[5]}]
set_property PACKAGE_PIN AA22 [get_ports {sa[6]}]
set_property PACKAGE_PIN AB11 [get_ports {sb[3]}]
set_property PACKAGE_PIN AA11 [get_ports {sb[4]}]
set_property PACKAGE_PIN AA7 [get_ports {sb[2]}] 
set_property PACKAGE_PIN AB2 [get_ports {sb[1]}]
set_property PACKAGE_PIN AB1 [get_ports {sb[0]}]
set_property PACKAGE_PIN AB5 [get_ports {sb[5]}]
set_property PACKAGE_PIN AB7 [get_ports {sb[6]}]
set_property PACKAGE_PIN U14 [get_ports {led_bus[7]}]
set_property PACKAGE_PIN U19 [get_ports {led_bus[6]}]
set_property PACKAGE_PIN W22 [get_ports {led_bus[5]}]
set_property PACKAGE_PIN V22 [get_ports {led_bus[4]}]
set_property PACKAGE_PIN U21 [get_ports {led_bus[3]}]
set_property PACKAGE_PIN U22 [get_ports {led_bus[2]}]
set_property PACKAGE_PIN T21 [get_ports {led_bus[1]}]
set_property PACKAGE_PIN T22 [get_ports {led_bus[0]}]
set_property PACKAGE_PIN R16 [get_ports click_b]
set_property PACKAGE_PIN Y9  [get_ports clk]
set_property PACKAGE_PIN T18 [get_ports click_a]
set_property PACKAGE_PIN F22 [get_ports rst]
set_property PACKAGE_PIN G22 [get_ports mode1]
set_property PACKAGE_PIN H22 [get_ports mode2]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sa[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bus[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports click_a]
set_property IOSTANDARD LVCMOS33 [get_ports click_b]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports mode1]
set_property IOSTANDARD LVCMOS33 [get_ports mode2]




set_property PACKAGE_PIN W20 [get_ports {sa[3]}]
set_property PACKAGE_PIN W21 [get_ports {sa[4]}]
set_property PACKAGE_PIN U20 [get_ports {sa[2]}]
set_property PACKAGE_PIN V20 [get_ports {sa[1]}]
set_property PACKAGE_PIN V18 [get_ports {sa[0]}]
set_property PACKAGE_PIN V19 [get_ports {sa[5]}]
set_property PACKAGE_PIN AA22 [get_ports {sa[6]}]
#set_property PACKAGE_PIN AA11 [get_ports {sb[3]}]
set_property PACKAGE_PIN AB4 [get_ports {sb[3]}]
set_property PACKAGE_PIN AB11 [get_ports {sb[4]}]
set_property PACKAGE_PIN AA7 [get_ports {sb[2]}] 
set_property PACKAGE_PIN AB2 [get_ports {sb[1]}]
set_property PACKAGE_PIN AB1 [get_ports {sb[0]}]
set_property PACKAGE_PIN AB5 [get_ports {sb[5]}]
set_property PACKAGE_PIN AB7 [get_ports {sb[6]}]
set_property PACKAGE_PIN U14 [get_ports {led_bus[7]}]
set_property PACKAGE_PIN U19 [get_ports {led_bus[6]}]
set_property PACKAGE_PIN W22 [get_ports {led_bus[5]}]
set_property PACKAGE_PIN V22 [get_ports {led_bus[4]}]
set_property PACKAGE_PIN U21 [get_ports {led_bus[3]}]
set_property PACKAGE_PIN U22 [get_ports {led_bus[2]}]
set_property PACKAGE_PIN T21 [get_ports {led_bus[1]}]
set_property PACKAGE_PIN T22 [get_ports {led_bus[0]}]
set_property PACKAGE_PIN R16 [get_ports click_b]
set_property PACKAGE_PIN Y9  [get_ports clk]
set_property PACKAGE_PIN T18 [get_ports click_a]
set_property PACKAGE_PIN F22 [get_ports rst]
set_property PACKAGE_PIN G22 [get_ports mode1]
set_property PACKAGE_PIN H22 [get_ports mode2]

set_property PACKAGE_PIN Y5  [get_ports {hsync}] 
set_property IOSTANDARD LVCMOS33 [get_ports {hsync}]

set_property PACKAGE_PIN W5 [get_ports {vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {vsync}]


set_property PACKAGE_PIN AB10   [get_ports {Rout[3]}]  
set_property PACKAGE_PIN AB9   [get_ports {Rout[2]}]  
set_property PACKAGE_PIN AA6 [get_ports {Rout[1]}]  
set_property PACKAGE_PIN Y11  [get_ports {Rout[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {Rout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Rout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Rout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Rout[0]}]


set_property PACKAGE_PIN Y10 [get_ports {Gout[3]}]  
set_property PACKAGE_PIN AB6 [get_ports {Gout[2]}]  
set_property PACKAGE_PIN Y4 [get_ports {Gout[1]}]  
set_property PACKAGE_PIN AA4 [get_ports {Gout[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {Gout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Gout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Gout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Gout[0]}]

set_property PACKAGE_PIN R6  [get_ports {Bout[3]}]  
set_property PACKAGE_PIN T6 [get_ports {Bout[2]}]  
set_property PACKAGE_PIN U4  [get_ports {Bout[1]}]  
set_property PACKAGE_PIN AA11  [get_ports {Bout[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {Bout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bout[0]}]